spring:
  cloud:
    gateway:
      enabled: true
      routes:
      # =====================================
      - id: foo-routes
        uri: lb://foo
        predicates:
        - Path=/foo/{segment}
      discovery:
        locator:
          enabled: true
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
