info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples
spring:
  cloud:
      etcd:
         uris: http://${etcd.host:192.168.163.128}:${etcd.port:2379}
         discovery:
            preferIpAddress: true
  boot:
       admin:
            url: http://${admin.host:10.41.1.213}:${admin.port:8090}


