server: 
  port: ${port:8090}
info:
  info: 监控服务
  version: 1.0
security: 
  ignored: /api/**
  user: 
      name: ${admin.username:admin}
      password: ${admin.password:Rlian123}
spring:
  jackson:
    serialization: 
      indent-output: true
endpoints: 
   health: 
       sensitive: false