server: 
  port: ${port:8090}
info:
  info: 监控服务
  version: 1.0
security: 
  ignored: /api/**
  user: 
      name: ${admin.username:admin}
      password: '{cipher}AQBh1HFMUeAF1QRZKQ8qTDd0CWURcSArRG/taVROzxni7xDTA1OxqxRCk6RXxWqoWcoFBjAdL3RXnNBLXZTkIwzi61uBydCF/0he6WCIirKQh0xdeixmITlJSD960XtGFR1WI+BqC0S0Y4jpE2SxG5XBvL395m9ieT1w9hFzvSK7pdYEFdzlinaM634zNGpm1tAfVG2b9ZaH8Qp7Aupr79xdbIvyVjgJ4pNes2cH3lDMAIHk5z94AV51jTBA+1eaHn38T16RneGWPjfWJA1VuQy/EsAg6YsCgN99OuTyfNu1R1R3/jch7ikPGnbRsuvC/GqSOhndSfcqiSQXLke4e+kSuT6UGl4DLuhadyeXJOTkW4NeQzkQyLdTUSKVFlccd84=}'
spring:
  jackson:
    serialization: 
      indent-output: true
endpoints: 
   health: 
       sensitive: false